dist: bionic

addons:
  apt:
    packages:
      - libzmq3-dev

language: cpp

compiler: gcc

before_install:
        - sudo apt update
        - sudo apt -y install libpugixml-dev python3-venv libboost-program-options-dev libboost-system-dev

before_script:
        - mkdir systemc
        - wget https://accellera.org/images/downloads/standards/systemc/systemc-2.3.3.tar.gz
        - tar -xf systemc-2.3.3.tar.gz
        - cd systemc-2.3.3
        - mkdir objdir
        - cd objdir
        - ../configure --prefix=/usr/local/systemc-2.3.3 --enable-static CXXFLAGS="-std=c++17"
        - make -j
        - sudo mkdir /usr/local/systemc-2.3.3
        - sudo make install
        - cd ../..

script:
        - make
        - source source_me.sh
        - python setup.py install
        - export SYSTEMC_DISABLE_COPYRIGHT_MESSAGE=1
        - cd ./ratatoskr/simulator
        - git checkout new-features-2021-01
        - ./build.sh
        - cd ../../tutorials/
        - jupyter nbconvert --to notebook --inplace --execute tutorial1.ipynb
        - jupyter nbconvert --to notebook --inplace --execute tutorial3.ipynb
        - cd ../ratatoskr/simulator
        - cmake -DDEFINE_ENABLE_NETRACE=ON
        - make
        - cd ../../tutorials
        - jupyter nbconvert --to notebook --inplace --execute tutorial4.ipynb